trigger: none

pool:
  vmImage: "ubuntu-latest"

variables:
  DOCKER_BUILDKIT: 1
  
steps:
  - task: Docker@2
    displayName: Build docker image
    inputs:
      command: 'build'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(Build.BuildId)
